data_kwargs.splits: [0.6, 0.3, 0.1]
dataloader_kwargs.batch_size: 16
early_stopping_kwargs.clf_kwargs.patience: 800
graph_clf_kwargs.dropout: 0.0
graph_clf_kwargs.has_bn: True
graph_clf_kwargs.hidden_dim: 128
graph_clf_kwargs.layers_gnn_num: 3
graph_clf_kwargs.pooling: ['mean', 'add']
lr_scheduler_kwargs_clf.factor: 0.95
lr_scheduler_kwargs_rl.factor: 0.95
optimizer_kwargs_clf.lr: 0.0001
optimizer_kwargs_rl.lr_clf: 0.0001
data: bzr
graph_clf: gin
cores.gnn_mode: True
graph_clf_kwargs.eps: 0.3
graph_clf_kwargs.train_eps: False
