data_kwargs.splits: [0.4, 0.5, 0.1]
dataloader_kwargs.batch_size: 16
early_stopping_kwargs.clf_kwargs.patience: 650
graph_clf_kwargs.dropout: 0.2
graph_clf_kwargs.has_bn: False
graph_clf_kwargs.hidden_dim: 64
graph_clf_kwargs.layers_gnn_num: 1
graph_clf_kwargs.pooling: ['add']
lr_scheduler_kwargs_clf.factor: 0.99
lr_scheduler_kwargs_rl.factor: 0.99
optimizer_kwargs_clf.lr: 0.001
optimizer_kwargs_rl.lr_clf: 0.001
data: cox2
graph_clf: gin
cores.gnn_mode: True
graph_clf_kwargs.eps: 0.2
graph_clf_kwargs.train_eps: True
