data_kwargs.splits: [0.6, 0.3, 0.1]
dataloader_kwargs.batch_size: 32
early_stopping_kwargs.clf_kwargs.patience: 650
graph_clf_kwargs.dropout: 0.2
graph_clf_kwargs.has_bn: True
graph_clf_kwargs.heads: 4
graph_clf_kwargs.hidden_dim: 128
graph_clf_kwargs.layers_gnn_num: 4
graph_clf_kwargs.pooling: ['add']
lr_scheduler_kwargs_clf.factor: 0.95
lr_scheduler_kwargs_rl.factor: 0.95
optimizer_kwargs_clf.lr: 0.005
optimizer_kwargs_rl.lr_clf: 0.005
data: nci1
graph_clf: gat
cores.gnn_mode: True
