data_kwargs.splits: [0.4, 0.5, 0.1]
dataloader_kwargs.batch_size: 32
early_stopping_kwargs.clf_kwargs.patience: 650
graph_clf_kwargs.dropout: 0.5
graph_clf_kwargs.has_bn: False
graph_clf_kwargs.hidden_dim: 32
graph_clf_kwargs.layers_gnn_num: 1
graph_clf_kwargs.pooling: ['mean']
lr_scheduler_kwargs_clf.factor: 0.99
lr_scheduler_kwargs_rl.factor: 0.99
optimizer_kwargs_clf.lr: 0.01
optimizer_kwargs_rl.lr_clf: 0.01
data: ptc_fm
graph_clf: gcn
cores.gnn_mode: True
