data_kwargs.splits: [0.5, 0.4, 0.1]
dataloader_kwargs.batch_size: 16
early_stopping_kwargs.clf_kwargs.patience: 800
graph_clf_kwargs.dropout: 0.5
graph_clf_kwargs.has_bn: True
graph_clf_kwargs.heads: 4
graph_clf_kwargs.hidden_dim: 16
graph_clf_kwargs.layers_gnn_num: 4
graph_clf_kwargs.pooling: ['mean', 'add']
lr_scheduler_kwargs_clf.factor: 0.9
lr_scheduler_kwargs_rl.factor: 0.9
optimizer_kwargs_clf.lr: 0.01
optimizer_kwargs_rl.lr_clf: 0.01
data: ptc_fm
graph_clf: gat
cores.gnn_mode: True
