data:
  distribution: constant
  value: ptc_fm
data_kwargs.balance:
  distribution: constant
  value: upsample
dataloader_kwargs.batch_size:
    distribution: categorical
    values: [16, 32]
loss:
  distribution: constant
  value: bce_logits
metrics:
  distribution: constant
  value: clf_binary
  