data_kwargs.splits: [0.5, 0.4, 0.1]
early_stopping_kwargs.ppo_kwargs.metric: training/ppo_loss___min
early_stopping_kwargs.ppo_kwargs.patience: 15
cores.env_steps: 128
cores.ppo_steps: 15
graph_env_kwargs.penalty_size: 0.5
lr_scheduler_kwargs_rl.factor: 0.9
optimizer_kwargs_rl.ratio_clf: 2.5
optimizer_kwargs_rl.ratio_critic: 3.0
ppo_kwargs.coeff_entropy: 0.0001
ppo_kwargs.coeff_mse: 0.1
ppo_kwargs.eps_clip: 0.3
reward_kwargs.alpha: 0.1
reward_kwargs.desired_ratio: 0.7
reward_kwargs.lambda_1: 0.6
data: mutag
graph_clf: gin
cores.action_refers_to: edge
reward_kwargs.k: 1.0
