data_kwargs.splits: [0.4, 0.5, 0.1]
early_stopping_kwargs.ppo_kwargs.metric: training/ppo_rewards___max
early_stopping_kwargs.ppo_kwargs.patience: 15
cores.env_steps: 32
cores.ppo_steps: 3
graph_env_kwargs.penalty_size: 0.5
lr_scheduler_kwargs_rl.factor: 0.99
optimizer_kwargs_rl.ratio_clf: 1.5
optimizer_kwargs_rl.ratio_critic: 3.0
ppo_kwargs.coeff_entropy: 0.01
ppo_kwargs.coeff_mse: 1.0
ppo_kwargs.eps_clip: 0.1
reward_kwargs.alpha: 0.1
reward_kwargs.desired_ratio: 0.4
reward_kwargs.lambda_1: 0.8
data: nci1
graph_clf: gcn
cores.action_refers_to: node
reward_kwargs.k: 1.0
