data_kwargs.splits: [0.4, 0.5, 0.1]
early_stopping_kwargs.ppo_kwargs.metric: training/ppo_rewards___max
early_stopping_kwargs.ppo_kwargs.patience: 15
cores.env_steps: 64
cores.ppo_steps: 5
graph_env_kwargs.penalty_size: 1.5
lr_scheduler_kwargs_rl.factor: 0.99
optimizer_kwargs_rl.ratio_clf: 1.0
optimizer_kwargs_rl.ratio_critic: 1.0
ppo_kwargs.coeff_entropy: 0.0001
ppo_kwargs.coeff_mse: 1.0
ppo_kwargs.eps_clip: 0.2
reward_kwargs.alpha: 0.1
reward_kwargs.desired_ratio: 0.3
reward_kwargs.lambda_1: 0.3
data: proteins
graph_clf: gin
cores.action_refers_to: edge
reward_kwargs.k: 5.0
