data_kwargs.splits: [0.5, 0.4, 0.1]
dataloader_kwargs.batch_size: 16
early_stopping_kwargs.patience: 500
graph_clf_kwargs.dropout: 0.0
graph_clf_kwargs.has_bn: True
graph_clf_kwargs.hidden_dim: 16
graph_clf_kwargs.layers_gnn_num: 2
graph_clf_kwargs.pooling: ['mean', 'add']
lr_scheduler_kwargs.factor: 0.9
optimizer_kwargs.lr: 0.005
top_k.multiplier: 2.0
top_k.ratio: 0.4
graph_clf_kwargs.heads: 4
data: bzr
graph_clf: gat
top_k.use_gnn: False
