data_kwargs.splits: [0.5, 0.4, 0.1]
dataloader_kwargs.batch_size: 16
early_stopping_kwargs.patience: 800
graph_clf_kwargs.dropout: 0.2
graph_clf_kwargs.has_bn: True
graph_clf_kwargs.hidden_dim: 32
graph_clf_kwargs.layers_gnn_num: 4
graph_clf_kwargs.pooling: ['mean']
lr_scheduler_kwargs.factor: 0.9
optimizer_kwargs.lr: 0.001
top_k.multiplier: 1.5
top_k.ratio: 0.3
data: bzr
graph_clf: gin
top_k.use_gnn: True
graph_clf_kwargs.eps: 0.4
graph_clf_kwargs.train_eps: False
