data_kwargs.splits: [0.4, 0.5, 0.1]
dataloader_kwargs.batch_size: 32
early_stopping_kwargs.patience: 800
graph_clf_kwargs.dropout: 0.5
graph_clf_kwargs.has_bn: False
graph_clf_kwargs.hidden_dim: 16
graph_clf_kwargs.layers_gnn_num: 3
graph_clf_kwargs.pooling: ['mean', 'add']
lr_scheduler_kwargs.factor: 0.99
model_kwargs.multiplier: 2.0
model_kwargs.ratio: 0.8
optimizer_kwargs.lr: 0.001
graph_clf_kwargs.heads: 2
data: dd
graph_clf: gat
top_k.use_gnn: ratio
