data_kwargs.splits: [0.4, 0.5, 0.1]
dataloader_kwargs.batch_size: 16
early_stopping_kwargs.patience: 500
graph_clf_kwargs.dropout: 0.1
graph_clf_kwargs.has_bn: False
graph_clf_kwargs.hidden_dim: 64
graph_clf_kwargs.layers_gnn_num: 2
graph_clf_kwargs.pooling: ['mean', 'add']
lr_scheduler_kwargs.factor: 0.9
optimizer_kwargs.lr: 0.01
top_k.multiplier: 2.0
top_k.ratio: 0.5
graph_clf_kwargs.heads: 1
data: dd
graph_clf: gat
top_k.use_gnn: True
