data_kwargs.splits: [0.5, 0.4, 0.1]
dataloader_kwargs.batch_size: 16
early_stopping_kwargs.patience: 800
graph_clf_kwargs.dropout: 0.4
graph_clf_kwargs.has_bn: True
graph_clf_kwargs.hidden_dim: 128
graph_clf_kwargs.layers_gnn_num: 4
graph_clf_kwargs.pooling: ['add']
lr_scheduler_kwargs.factor: 0.99
model_kwargs.multiplier: 2.0
model_kwargs.ratio: 0.9
optimizer_kwargs.lr: 0.01
graph_clf_kwargs.heads: 1
data: mutag
graph_clf: gat
top_k.use_gnn: ratio
