data_kwargs.splits: [0.5, 0.4, 0.1]
dataloader_kwargs.batch_size: 32
early_stopping_kwargs.patience: 500
graph_clf_kwargs.dropout: 0.4
graph_clf_kwargs.has_bn: False
graph_clf_kwargs.hidden_dim: 16
graph_clf_kwargs.layers_gnn_num: 2
graph_clf_kwargs.pooling: ['mean', 'add']
lr_scheduler_kwargs.factor: 0.99
optimizer_kwargs.lr: 0.005
top_k.multiplier: 0.5
top_k.ratio: 0.8
graph_clf_kwargs.heads: 4
data: nci109
graph_clf: gat
top_k.use_gnn: True
