data_kwargs.splits: [0.5, 0.4, 0.1]
dataloader_kwargs.batch_size: 16
early_stopping_kwargs.patience: 650
graph_clf_kwargs.dropout: 0.0
graph_clf_kwargs.has_bn: False
graph_clf_kwargs.hidden_dim: 32
graph_clf_kwargs.layers_gnn_num: 1
graph_clf_kwargs.pooling: ['mean', 'add']
lr_scheduler_kwargs.factor: 0.95
optimizer_kwargs.lr: 0.005
top_k.multiplier: 2.0
top_k.ratio: 0.95
data: nci1
graph_clf: gcn
top_k.use_gnn: True
