data_kwargs.splits: [0.4, 0.5, 0.1]
dataloader_kwargs.batch_size: 32
early_stopping_kwargs.patience: 500
graph_clf_kwargs.dropout: 0.3
graph_clf_kwargs.has_bn: True
graph_clf_kwargs.hidden_dim: 128
graph_clf_kwargs.layers_gnn_num: 3
graph_clf_kwargs.pooling: ['mean', 'add']
lr_scheduler_kwargs.factor: 0.9
model_kwargs.multiplier: 0.5
model_kwargs.ratio: 0.7
optimizer_kwargs.lr: 0.001
graph_clf_kwargs.heads: 1
data: nci1
graph_clf: gat
top_k.use_gnn: ratio
