data_kwargs.splits: [0.5, 0.4, 0.1]
dataloader_kwargs.batch_size: 16
early_stopping_kwargs.patience: 650
graph_clf_kwargs.dropout: 0.1
graph_clf_kwargs.has_bn: True
graph_clf_kwargs.hidden_dim: 128
graph_clf_kwargs.layers_gnn_num: 4
graph_clf_kwargs.pooling: ['mean']
lr_scheduler_kwargs.factor: 0.95
optimizer_kwargs.lr: 0.0001
top_k.multiplier: 1.5
top_k.ratio: 0.3
data: nci109
graph_clf: gcn
top_k.use_gnn: True
