data_kwargs.splits: [0.6, 0.3, 0.1]
dataloader_kwargs.batch_size: 16
early_stopping_kwargs.patience: 650
graph_clf_kwargs.dropout: 0.1
graph_clf_kwargs.has_bn: True
graph_clf_kwargs.hidden_dim: 32
graph_clf_kwargs.layers_gnn_num: 3
graph_clf_kwargs.pooling: ['mean']
lr_scheduler_kwargs.factor: 0.95
optimizer_kwargs.lr: 0.0001
top_k.multiplier: 1.5
top_k.ratio: 0.6
graph_clf_kwargs.heads: 1
data: nci1
graph_clf: gat
top_k.use_gnn: True
