data_kwargs.splits: [0.6, 0.3, 0.1]
dataloader_kwargs.batch_size: 16
early_stopping_kwargs.patience: 800
graph_clf_kwargs.dropout: 0.1
graph_clf_kwargs.has_bn: True
graph_clf_kwargs.hidden_dim: 64
graph_clf_kwargs.layers_gnn_num: 3
graph_clf_kwargs.pooling: ['add']
lr_scheduler_kwargs.factor: 0.9
model_kwargs.multiplier: 0.5
model_kwargs.ratio: 0.8
optimizer_kwargs.lr: 0.001
graph_clf_kwargs.heads: 4
data: nci109
graph_clf: gat
top_k.use_gnn: ratio
