data_kwargs.splits: [0.4, 0.5, 0.1]
dataloader_kwargs.batch_size: 32
early_stopping_kwargs.patience: 800
graph_clf_kwargs.dropout: 0.5
graph_clf_kwargs.has_bn: True
graph_clf_kwargs.hidden_dim: 16
graph_clf_kwargs.layers_gnn_num: 3
graph_clf_kwargs.pooling: ['mean', 'add']
lr_scheduler_kwargs.factor: 0.99
optimizer_kwargs.lr: 0.001
top_k.multiplier: 0.5
top_k.ratio: 0.5
data: proteins
graph_clf: gcn
top_k.use_gnn: False
