data_kwargs.splits: [0.4, 0.5, 0.1]
dataloader_kwargs.batch_size: 16
early_stopping_kwargs.patience: 800
graph_clf_kwargs.dropout: 0.3
graph_clf_kwargs.has_bn: False
graph_clf_kwargs.hidden_dim: 16
graph_clf_kwargs.layers_gnn_num: 1
graph_clf_kwargs.pooling: ['mean', 'add']
lr_scheduler_kwargs.factor: 0.9
optimizer_kwargs.lr: 0.01
top_k.multiplier: 1.0
top_k.ratio: 0.9
graph_clf_kwargs.heads: 1
data: proteins
graph_clf: gat
top_k.use_gnn: True
