data_kwargs.splits: [0.4, 0.5, 0.1]
dataloader_kwargs.batch_size: 32
early_stopping_kwargs.patience: 650
graph_clf_kwargs.dropout: 0.1
graph_clf_kwargs.has_bn: False
graph_clf_kwargs.hidden_dim: 16
graph_clf_kwargs.layers_gnn_num: 1
graph_clf_kwargs.pooling: ['add']
lr_scheduler_kwargs.factor: 0.95
optimizer_kwargs.lr: 0.001
top_k.multiplier: 1.5
top_k.ratio: 0.5
graph_clf_kwargs.heads: 1
data: proteins
graph_clf: gat
top_k.use_gnn: False
