data_kwargs.splits: [0.6, 0.3, 0.1]
dataloader_kwargs.batch_size: 32
early_stopping_kwargs.patience: 650
graph_clf_kwargs.dropout: 0.4
graph_clf_kwargs.has_bn: False
graph_clf_kwargs.hidden_dim: 64
graph_clf_kwargs.layers_gnn_num: 3
graph_clf_kwargs.pooling: ['mean']
lr_scheduler_kwargs.factor: 0.9
model_kwargs.multiplier: 2.0
model_kwargs.ratio: 0.9
optimizer_kwargs.lr: 0.0001
graph_clf_kwargs.heads: 4
data: ptc_fm
graph_clf: gat
top_k.use_gnn: ratio
