data_kwargs.splits: [0.6, 0.3, 0.1]
dataloader_kwargs.batch_size: 16
early_stopping_kwargs.patience: 650
graph_clf_kwargs.dropout: 0.1
graph_clf_kwargs.has_bn: False
graph_clf_kwargs.hidden_dim: 16
graph_clf_kwargs.layers_gnn_num: 3
graph_clf_kwargs.pooling: ['mean']
lr_scheduler_kwargs.factor: 0.95
optimizer_kwargs.lr: 0.005
top_k.multiplier: 1.5
top_k.ratio: 0.8
data: ptc_fm
graph_clf: gcn
top_k.use_gnn: False
