data_kwargs.splits: [0.6, 0.3, 0.1]
dataloader_kwargs.batch_size: 32
early_stopping_kwargs.patience: 650
graph_clf_kwargs.dropout: 0.4
graph_clf_kwargs.has_bn: False
graph_clf_kwargs.hidden_dim: 64
graph_clf_kwargs.layers_gnn_num: 3
graph_clf_kwargs.pooling: ['mean']
lr_scheduler_kwargs.factor: 0.9
optimizer_kwargs.lr: 0.0001
top_k.multiplier: 0.5
top_k.ratio: 0.2
data: ptc_fm
graph_clf: gcn
top_k.use_gnn: True
